### ISSUE TITLE
Support for arm64

### ISSUE THREAD

**Issue by khanhldt** [project-imas/security-check#3]
Hi, we're using this library as one of our protection strategies in our products. Apparently the assembly instruction set for arm64 has changed for the ones used by this library. Will you be able to provide an update for this?

Thanks!

**Comment by Emmo213** [comment]
I recently did a pull of this project and now am receiving errors when using on the simulator. Here are the errors I'm receiving. If there are any ideas on how to resolve I would appreciate them. Thank you.

/security-check/SecurityCheck/readSys.s:24:17: error: brackets expression not supported on this target
    stp fp, lr, [sp, #-16]!
                ^
/security-check/SecurityCheck/readSys.s:25:17: error: unknown token in expression
    add fp, sp, #0
                ^
/security-check/SecurityCheck/readSys.s:27:13: error: unknown token in expression
    mov x4, #0
            ^
/security-check/SecurityCheck/readSys.s:28:13: error: unknown token in expression
    mov x5, #0
            ^
/security-check/SecurityCheck/readSys.s:29:14: error: unknown token in expression
    mov x16, #202
             ^
/security-check/SecurityCheck/readSys.s:30:5: error: invalid instruction mnemonic 'svc'
    svc #128
    ^~~
/security-check/SecurityCheck/readSys.s:33:17: error: brackets expression not supported on this target
    ldp fp, lr, [sp], #16
                ^
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

**Comment by zerpt** [comment]
Hello @Emmo213 !
This was an issue with how Security Check was detecting target architecture. I've pushed a fix which seems to resolve the issue. Let me know if this doesn't work for you.

**Comment by Emmo213** [comment]
Yes, that solved my issue. Thank you very much, @zerpt!
